# Generated by Django 5.1.2 on 2024-10-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaccines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccines",
            name="description",
            field=models.TextField(),
        ),
    ]
