# Generated by Django 5.1.2 on 2024-10-31 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaccines", "0002_alter_vaccines_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarcVaccine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_date", models.DateField()),
                ("next_dose", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaccines",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vaccines.vaccines",
                    ),
                ),
            ],
        ),
    ]
